version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db:5432/ai_quizzer
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - GROQ_API_KEY=your_groq_api_key
      - EMAIL_FROM=your_email@example.com
      - SENDGRID_API_KEY=your_sendgrid_key
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_quizzer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: