services:
  - type: web
    name: aiquizzer
    runtime: docker
    env: node
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aiquizzer_db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false  # Set manually in Render dashboard